name: Terraform CI/CD

on:
  push:
    branches:
      - dev
      - staging
      - main
  pull_request:
    branches:
      - staging
      - main

  workflow_dispatch:
    inputs:
      force_apply:
        description: "Apply Terraform even if drift exists"
        required: false
        default: "false"

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.0

      - name: Determine environment
        id: env
        run: |
          if [[ "${GITHUB_REF_NAME}" == "dev" ]]; then
            echo "ENV=dev" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF_NAME}" == "staging" ]]; then
            echo "ENV=staging" >> $GITHUB_ENV
          else
            echo "ENV=prod" >> $GITHUB_ENV
          fi
          echo "Environment folder is ${{ env.ENV }}"

      - name: Terraform Init
        working-directory: envs/${{ env.ENV }}
        run: terraform init -input=false

      - name: Terraform Plan (Drift Detection)
        id: plan
        working-directory: envs/${{ env.ENV }}
        run: |
          terraform plan -detailed-exitcode -out=tfplan || exit_code=$?
          if [ "$exit_code" -eq 1 ]; then
            echo "Terraform plan failed!"
            exit 1
          elif [ "$exit_code" -eq 2 ]; then
            echo "Drift detected or changes found. Stopping pipeline."
            echo "DRIFT=true" >> $GITHUB_ENV
            exit 2
          else
            echo "No drift detected."
            echo "DRIFT=false" >> $GITHUB_ENV
          fi

      - name: Stop if drift detected
        if: env.DRIFT == 'true'
        run: |
          echo "Drift found! Deployment halted."
          echo "Fix the drift manually or update Terraform code."
          exit 1

      - name: Terraform Apply
        if: env.DRIFT == 'false'
        working-directory: envs/${{ env.ENV }}
        run: terraform apply -auto-approve tfplan

